-- New Companies
-- https://www.hackerrank.com/challenges/the-company/problem?isFullScreen=true

SELECT      COMPANY_CODE, 
            FOUNDER,
            (SELECT COUNT(DISTINCT(LEAD_MANAGER_CODE)) FROM LEAD_MANAGER lm WHERE c.COMPANY_CODE = lm.COMPANY_CODE) AS LM_COUNT,
            (SELECT COUNT(DISTINCT(SENIOR_MANAGER_CODE)) FROM SENIOR_MANAGER sm WHERE c.COMPANY_CODE = sm.COMPANY_CODE) AS SM_COUNT,
            (SELECT COUNT(DISTINCT(MANAGER_CODE)) FROM MANAGER m WHERE c.COMPANY_CODE = m.COMPANY_CODE) AS M_COUNT,
            (SELECT COUNT(DISTINCT(EMPLOYEE_CODE)) FROM EMPLOYEE e WHERE c.COMPANY_CODE = e.COMPANY_CODE) AS E_COUNT
FROM        COMPANY c
ORDER BY    COMPANY_CODE;